DROP TABLE IF EXISTS books;
CREATE TABLE books (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE NOT NULL,
  title TEXT NOT NULL,
  author TEXT NOT NULL,
  genre TEXT,
  price FLOAT,
  num_in_stock INT,
  publisher TEXT,
  year_published INTEGER,
  print_edition INT,
  text_language TEXT
);